### ISSUE TITLE
Over discharge protection?

### ISSUE THREAD

**Issue by ghost** [Arnold-n/Covid-CO2#1]
I just assembled one of these and left it running on battery power overnight. This morning, it seemed to be dead, but after charging it for roughly 20 minutes, it looks like it is mostly charged. So now I'm wondering if the charge & boost circuit has over-discharge protection.

**Comment by ArnoldNiessen** [comment]
Thanks for your feedback! The boost circuit does not have over-discharge protection, the design relies on the built-in circuitry of the battery. Some batteries may cycle up and down a few times when empty. When the battery is empty and just being charged, the voltage to the boost circuit may be low, and the current used by the boost circuit may be more than the charge circuit can provide to ESP+battery, so the ESP needs to be powered off for perhaps 10 minutes until the battery voltage is high enough. I'll add this explanation to the readme.

**Comment by ghost** [comment]
Cool, that makes sense. What kind of battery life are you getting?

**Comment by ArnoldNiessen** [comment]
Around 4 hours I guess, did not measure it. Enough for store visits. Deepsleep should lengthen it. At home they are USB-powered (and will cycle in full state, I don't know what this means for battery life time).
