### ISSUE TITLE
Tasmota Configuration

### ISSUE THREAD

**Issue by g0lgs** [Arnold-n/Covid-CO2#2]
Can you make your user_config_override.h or platformio_override.ini or whatever settings you used to build a version of Tasmota with the required options available ?

**Comment by Arnold-n** [comment]
The file user_config_override.h is already present in the CO2 branch of my Tasmota fork. Depending on the sensor, use one of:
[MHZ19B with ABC disabled](https://github.com/Arnold-n/Tasmota/blob/CO2/tasmota/user_config_override_MHZ19B_ABC_disabled.h)
[MHZ19B with ABC enabled](https://github.com/Arnold-n/Tasmota/blob/CO2/tasmota/user_config_override_MHZ19B_ABC_enabled.h)
[S8](https://github.com/Arnold-n/Tasmota/blob/CO2/tasmota/user_config_override_S8.h)
[SCD30](https://github.com/Arnold-n/Tasmota/blob/CO2/tasmota/user_config_override_SCD30.h)
These scripts were written for this CO2 branch and require the options PRECONFIGURED_SCRIPT and MHZ19B_ABC_DISABLE which are supported by my CO2 branch but not by the stable Tasmota branch. The PRECONFIGURED_SCRIPT option is supported in Tasmota's current development branch.

I did not use any platformio_override.ini file.

For compilation I used the instructions from [docker-tasmota](https://github.com/tasmota/docker-tasmota).

**Comment by g0lgs** [comment]
Thanks for the link.
